version: "3.7"

services:
  php:
    env_file:
      - ../internal-docker/environment.dev
      - ../internal-docker/environment.dev.local
    environment:
      XDEBUG_SERVER_NAME: "verzuimsignaal2.docker.local"
      XDEBUG_AUTOSTART: "0"
    dns_search:
      - dev.is.verzuimsignaal.nl
  web:
    dns_search:
      - dev.is.verzuimsignaal.nl
